name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  build-lint:
    env:
      DATABASE_URL: file:./db.sqlite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: yarn install

      # Normally, this would be done as part of the turbo pipeline - however since the Expo app doesn't depend on `db` it doesn't care.
      # TODO: Free for all to find a better solution here.
      - name: Generate Prisma Client
        run: yarn turbo db:generate

      - name: Build, lint and type-check
        run: yarn turbo build lint type-check
        env:
          SKIP_ENV_VALIDATION: true

      - name: Check workspaces
        run: yarn manypkg check
